# Generated by Django 4.2.7 on 2023-11-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Electronic', 'Electronic'), ('Dairy', 'Dairy'), ('Snack', 'Snack'), ('Other', 'Other')], max_length=20)),
            ],
        ),
    ]
